Feature #22 retrieve user change history
Trazi-Ventures/travelling pull request #11
Opened 2021-07-01 22:58 UTC by theclayton

2021-07-12 15:47 UTC, Traziventures commented on include/routes/v1/functions/auth.js
> +        audit.createSingleAudit(auditObj);
dont you need to await?

2021-07-12 15:47 UTC, Traziventures commented on include/routes/v1/functions/auth.js
> +        audit.createSingleAudit(auditObj);
dont you need to await?

2021-07-19 19:57 UTC, Phara0h requested changes

2021-07-19 19:57 UTC, Phara0h commented on include/routes/v1/functions/users.js
> +  var oldModel = await getUser(opts);
Need a check for audit since if tis off no need to do extra stuff. ` if (config.audit.edit.enable === true) {`

2021-07-19 19:57 UTC, Phara0h commented on include/routes/v1/functions/users.js
> +    oldModel = { [opts.req.params.prop]: oldModel };
same check

2021-07-19 19:57 UTC, Phara0h commented on include/routes/v1/functions/auth.js
> +      subaction: 'USER_RESET_PASSWORD'
should include new and old password hashes.

2021-07-19 20:09 UTC, Phara0h commented on include/routes/v1/functions/groups.js
> +      if (config.audit.edit.enable === true) {
Should move this check above line 364 then you can use `fgroup._` and `dgroup._` to only get the changes for those object.

2021-07-19 20:15 UTC, Phara0h commented on include/routes/v1/functions/groups.js
> +  if (config.audit.edit.enable === true) {
if your going to use the req.body for this. call `exportGroups` to get the `old object` before everything gets saved. Dont forget to check for `config.audit.edit.enable` before you call `exportGroups`

2021-07-19 20:19 UTC, Phara0h commented on include/routes/v1/functions/users.js
> +        oldObj: oldModel,
same thing with the but with this one using the `._`

2021-07-19 20:21 UTC, Phara0h commented on include/routes/v1/functions/users.js
> +    if (config.audit.edit.enable === true) {
This should be capturing the users group old and new inheritance object.

2021-07-19 20:36 UTC, Phara0h requested changes

2021-07-19 20:36 UTC, Phara0h commented on include/routes/v1/audit.js
> +  });
it would be nice to get some routes in here to search by action and or subaction

2021-07-19 20:36 UTC, Phara0h commented on include/utils/audit.js
> +    JSON.stringify(str);
This is a super slow way to check if a object can be stringified.

2021-07-19 20:36 UTC, Phara0h commented on include/utils/audit.js
> +    if (isJson(oldPropValue)) {
Just stringify it and wrapp a try catch around it so it does not need to be stringified twice (once from calling `isJson` and once again from calling Json.stringify after it)

2021-07-19 20:36 UTC, Phara0h commented on tests/endpoints/auth-register.js
> +      const audit = await Audit.findAllBy({ of_user_id: u[0].id, action: "CREATE", subaction: "USER" });
This should fail if you have audit turned off. Make sure you test this.

2021-07-19 20:36 UTC, Phara0h commented on tests/endpoints/groups.js
> +        const audit = await Audit.findAllBy({ action: "CREATE", subaction: "GROUP" });
Sould do a if check in here to check the config if audit is turned on.

2021-07-19 20:36 UTC, Phara0h commented on tests/endpoints/user-edit.js
> +        const u = await User.findAllBy({ username: "test2" });
make this a sep test

2021-07-20 22:23 UTC, theclayton commented on include/routes/v1/functions/users.js
> +        oldObj: oldModel,
`_` seems to break it. I have logic to only save the unique props in splitAndCreateAudits.

2021-07-20 22:24 UTC, theclayton commented on include/routes/v1/functions/groups.js
> +      if (config.audit.edit.enable === true) {
Good catch

2021-07-20 22:25 UTC, theclayton commented on tests/endpoints/auth-register.js
> +      const audit = await Audit.findAllBy({ of_user_id: u[0].id, action: "CREATE", subaction: "USER" });
It does. Good call. I'll test with env variables on and off from now on.

2021-07-20 22:32 UTC, theclayton commented on include/routes/v1/audit.js
> +  });
Added routes for getting audits by action or sub action as well as action with subaction.

2021-07-22 18:01 UTC, Phara0h commented on include/routes/v1/functions/auth.js
> +          config.log.logger.info(`Failed Auth (${e.err.msg}): `, username, email, domain);
Change this to `config.log.logger.info(`Failed Auth (${e.err.msg}): ${username}, ${email}, ${domain}`);`

2021-07-22 18:08 UTC, Phara0h commented on include/routes/v1/functions/groups.js
> +        oldObj: fgroup,
should be  fgroup._

2021-07-22 18:09 UTC, Phara0h commented on include/routes/v1/functions/groups.js
> +        newObj: group
group._

2021-07-22 18:14 UTC, Phara0h commented on include/routes/v1/functions/groups.js
> +    previousGroup = fgroup;
This should be right above line 432 just above the fgroup.save(). so you can do `previousGroup = fgroup._` instead which will just be the changes persited to the database.

2021-07-22 18:18 UTC, Phara0h commented on include/routes/v1/functions/groups.js
> +
This should work just as edit does. right above save to capture the changes to the route.

2021-07-22 18:19 UTC, Phara0h commented on include/routes/v1/functions/groups.js
> +      oldObj: fgroup._
this will just be `fgroup`

2021-07-22 18:20 UTC, Phara0h commented on include/routes/v1/functions/groups.js
> +  if (config.audit.edit.enable === true) {
No need to capture this since we capture the change right above it in `editGroup`

2021-07-22 18:21 UTC, Phara0h commented on include/routes/v1/functions/groups.js
> +  if (config.audit.edit.enable === true) {
No need to capture this since we capture the change right above it in editGroup

2021-07-22 18:26 UTC, Phara0h commented on include/routes/v1/functions/users.js
> +      oldModel = { [opts.req.params.prop]: oldModel };
you need to do `oldModel[opts.req.params.prop]` so you dont get the hole user object and just the prop thats being edited.

2021-07-22 18:28 UTC, Phara0h commented on include/routes/v1/functions/users.js
> +        newObj: model
use `updatedProps` instead of model so yo u get the acutall data that the db is being updated with not the before mutations.

2021-07-22 18:36 UTC, Phara0h commented on include/routes/v1/functions/audit.js
> +    return await Audit.findAllBy(type);
Prob want to do some checking on these types and subtypes since we know them all and should not let any other thing be even attempted (security reasons). See utils/users.js for how I check each prop of an object before I do any kinda of searching with it.

2021-07-22 18:39 UTC, Phara0h commented on tests/endpoints/auth-register.js
> +    test('Create User Audit', async () => {
Should be called `Checking Audit of (Create Test User [test2])`

2021-07-22 20:48 UTC, theclayton commented on include/routes/v1/functions/users.js
> +      oldModel = { [opts.req.params.prop]: oldModel };
To get `oldModel` I'm passing all the opts to the `getUser()` function which will return a single prop as a string in this case.

2021-07-30 20:45 UTC, Phara0h commented on include/routes/v1/functions/users.js
> +  const changedProps = Object.assign({}, updatedProps);
Needs to be in a check  if (config.audit.edit.enable === true) {

2021-07-30 20:47 UTC, Phara0h commented on include/routes/v1/functions/users.js
> +      oldModel = { [opts.req.params.prop]: oldModel };
needs to be oldModel[opts.req.params.prop]

2021-07-30 21:16 UTC, merged